routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(array('prefix' => 'admin'), function() {
    Route::get('/', array('middleware' => 'guest.admin', 'uses' => 'Admin\LoginController@getIndex'));
    
    Route::get('logout', array('uses' => 'Admin\LoginController@doLogout'));
    Route::post('login', array('uses' => 'Admin\LoginController@doLogin'));
    Route::post('verifyOtp', array('uses' => 'Admin\LoginController@doVerifyOtp'));
    // Password Reset Routes...
    Route::get('password/reset', array('uses'=>'Admin\ForgotPasswordController@showLinkRequestForm', 'as'=>'admin.password.email'));
    Route::post('password/email', array('uses'=>'Admin\ForgotPasswordController@sendResetOtp', 'as'=>'admin.password.email'));
    Route::post('password/generate', array('uses'=>'Admin\ForgotPasswordController@verifyOtp', 'as'=>'admin.password.reset'));
    Route::post('makeNewPassword', array('uses'=>'Admin\ForgotPasswordController@makeNewPassword', 'as'=>'admin.password.reset'));

    //after login
    Route::group(array('middleware' => 'auth.admin'), function() {
    Route::get('dashboard', 'Admin\DashboardController@index');
        // Rides Management 
        Route::get('rides-management','Admin\RidesController@index');
        Route::get('rides-management/rides-data','Admin\RidesController@ridesData');
        Route::delete('rides-management/ride/{id}','Admin\RidesController@rideDelete');
        Route::get('rides-management/edit/{id}','Admin\RidesController@edit');
        Route::put('rides-management/ride','Admin\RidesController@update')->name('admin/rides-management/ride');
    
        // Settings Management
        Route::resource('settings', 'Admin\SettingsController');
        
        // Admin Profile Management
        Route::resource('profile', 'Admin\ProfileController');
        
        // Admin password change
        Route::get('password/change', array('uses' => 'Admin\ProfileController@changePassword', 'as' => 'admin.password.change'));
        Route::post('password/change', array('uses' => 'Admin\ProfileController@updatePassword', 'as' => 'admin.password.change'));
        
        // Services Management
        Route::get('services/ServicesData', 'Admin\ServicesController@getServicesData');
        Route::post('services/changeStatus', 'Admin\ServicesController@changeServiceStatus');
        Route::resource('services','Admin\ServicesController');
        
        Route::post('servicesCategory/changeStatus', 'Admin\ServiceCategoryController@changeServiceStatus');
        Route::get('listCategory', 'Admin\ServiceCategoryController@index')->name('listCategory');
        Route::get('addCategory', 'Admin\ServiceCategoryController@create')->name('addCategory');
        Route::post('saveCategory', 'Admin\ServiceCategoryController@saveCategory')->name('saveCategory');
        Route::get('editCategory/{id}', 'Admin\ServiceCategoryController@editCategory')->name('editCategory');
        Route::post('updateCategory', 'Admin\ServiceCategoryController@updateCategory')->name('updateCategory');
        Route::get('deleteCategory/{id}', 'Admin\ServiceCategoryController@deleteCategory')->name('deleteCategory');
        
        // Booking Management
        Route::get('booking/export', 'Admin\BookingController@export');
        Route::any('booking/search', array('uses' => 'Admin\BookingController@search', 'as' => 'admin.booking.search'));
        Route::post('booking/changeStatus', 'Admin\BookingController@changeBookingStatus');
        
        Route::resource('appointments','Admin\BookingController');
        
        // Transaction Management
        Route::get('transaction/export', 'Admin\TransactionController@export');
        Route::any('transaction/search', array('uses' => 'Admin\TransactionController@search', 'as' => 'admin.transaction.search'));
        Route::resource('transaction','Admin\TransactionController');
        
        // User Management
        Route::post('users/updateCredit', 'Admin\UserController@updateCredit');
        Route::get('users/UserData', 'Admin\UserController@getUserData');
        Route::get('vendors/VendorData', 'Admin\VendorController@getVendorData');
        
        Route::get('bookings/BookingData', 'Admin\BookingController@getBookingData');

        Route::post('users/changeStatus', 'Admin\UserController@changeUserStatus');
        Route::get('users/show/{id}', 'Admin\UserController@show');
        Route::get('users/showuser/{id}', 'Admin\UserController@showuser');
        Route::resource('users', 'Admin\UserController');
        Route::any('user/Add', 'Admin\UserController@Add');
        Route::any('user/addUser', 'Admin\UserController@AddUser');
        Route::any('user/edit/{id}', 'Admin\UserController@edit');
        Route::any('user/update/{id}', 'Admin\UserController@update');
		Route::any('user/view/{id}','Admin\UserController@view');
        Route::any('userReport','Admin\UserController@userReport');
        Route::post('users/changeStatus', 'Admin\UserController@changeUserStatus');
        
        //Notifications Management
        Route::get('notifications/{type}', 'Admin\NotificationController@getNotifications');
        Route::get('sendNotifications', 'Admin\NotificationController@fetchNotification');
        Route::POST('sendNotifications', 'Admin\NotificationController@sendNotification');
 
        //faq
        Route::get('faq','Admin\SettingsController@faq');
        Route::get('faqData','Admin\SettingsController@faqData');
        Route::get('faq/{id}/edit','Admin\SettingsController@faqEdit');
        Route::post('faq/save-edit/{id}','Admin\SettingsController@faqSaveEdit');
        Route::get('faq/add','Admin\SettingsController@faqAdd');
        Route::post('faq/save-add','Admin\SettingsController@faqSaveAdd');
        Route::delete('faq/{id}','Admin\SettingsController@faqDelete');
        Route::any('deleteEdu','Admin\VendorController@deleteEdu');
        //referral_settings
        Route::get('referralSettings','Admin\SettingsController@showReferral');
        Route::POST('referralSettings','Admin\SettingsController@updateReferral');
        //ride_settings
        Route::get('rideSettings','Admin\SettingsController@showRideSettings');
        Route::POST('rideSettings','Admin\SettingsController@updateRideSettings');
        //performance, userIssues
        Route::get('performance','Admin\PerformanceController@showOverallPerformance');
        Route::get('usersIssues','Admin\GetInTouchController@showAllIssues');
        Route::get('getIssueRequestData','Admin\GetInTouchController@getIssueRequestData');
    });
});

/** ------------------------------------------
 *  Frontend Routes
 *  ------------------------------------------
 */
Route::get('/', function () {
    return redirect('admin.login');
});
//before login
Route::post('contact', array('uses' => 'Frontend\HomeController@submitEnquiry', 'as' => 'contact'));
Route::post('Notification', array('uses' => 'Frontend\HomeController@submitNotification', 'as' => 'Notification'));
//login user
Route::post('login', array('uses' => 'Frontend\LoginController@doLogin', 'as' => 'frontend.login'));
Route::resource('users', 'Frontend\UserController');
// Password Reset Routes...
Route::get('password/reset', array('uses'=>'Frontend\ForgotPasswordController@showLinkRequestForm', 'as'=>'password.email'));
Route::post('password/email', array('uses'=>'Frontend\ForgotPasswordController@sendResetLinkEmail', 'as'=>'password.email'));
Route::get('password/reset/{token}', array('uses'=>'Frontend\ResetPasswordController@showResetForm', 'as'=>'password.reset'));
Route::post('password/reset', array('uses'=>'Frontend\ResetPasswordController@reset', 'as'=>'password.reset'));
//after login
Route::group(array('middleware' => 'auth.user'), function() {
    Route::get('dashboard', 'FrontendDashboardController\DashboardController@index');
    Route::get('profile', 'Frontend\UserController@index');
    #user password change
    Route::get('password/change', array('uses' => 'Frontend\UserController@changePassword', 'as' => 'password.change'));
    Route::post('password/change', array('uses' => 'Frontend\UserController@updatePassword', 'as' => 'password.change'));
    #logout user
    Route::get('logout', 'Frontend\LoginController@doLogout');
});

resources/views/admin/changePassword.blade.php
@extends('admin.layouts.default')

{{-- Web site Title --}}
@section('title')
@parent :: {!! trans('admin/changePassword.change_password') !!}
@stop
@section('styles')
@stop
{{-- Content --}}
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>{!! trans('admin/changePassword.change_password') !!}</h1>
        <ol class="breadcrumb">
            <li><a href="{!!url('admin/dashboard/')!!}" style="color:white;"><span class="fa fa-dashboard"></span> {!! trans('admin/common.home') !!}</a></li>
            <li class="active" style="color:white;">{!! trans('admin/changePassword.change_password') !!}</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <div class="col-md-12">
                <!-- Notifications -->
                @include('admin.includes.notifications')
                <!-- ./ notifications -->
            </div>
            <div class="col-xs-12">
                <div class="box">
                        {!! Form::open(['route' => 'admin.password.change', 'id' => 'change-password-form', 'novalidate' => 'novalidate']) !!}
                    <div class="box-body">
                        <div class="form-group has-feedback">
                            {!! Form::label('password',trans('admin/changePassword.old_password')) !!}
                            {!! Form::password('old_password', array('class'=>'form-control','id' => 'old_password')) !!}
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>

                        <div class="form-group has-feedback">
                            {!! Form::label('password',trans('admin/changePassword.new_password')) !!}
                            {!! Form::password('password', array('class'=>'form-control','id' => 'password')) !!}
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>

                        <div class="form-group has-feedback">
                            {!! Form::label('cpassword',trans('admin/changePassword.confirm_password')) !!}
                            {!! Form::password('password_confirmation', array('class'=>'form-control','id' => 'password_confirmation')) !!}
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="box-footer">
                        {!! Form::submit(trans('admin/common.submit'),array('class'=>'btn btn-primary', 'id'=>'submitform')) !!}
                        <a href="{!! URL::route('admin.password.change') !!}" class="btn btn-default">{!! trans('admin/common.cancel') !!}</a>
                    </div>
                    {!! Form::close()!!}
                </div> <!-- /.box -->
            </div> <!-- /.col-xs-12 -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
@stop

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.default')
@section('title')
@parent :: {!! trans('admin/dashboard.dashboard') !!}
@stop
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Dashboard
            <small>Admin</small>
        </h1>

    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-4 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-fuchsia">
                    <div class="inner">
                        <h3>{!! $users !!}</h3>
                        <p>Total Users<br><br></p>
                    </div>
                    <div class="icon">
                        <span class="ion ion-person-add"></span>
                    </div>
                    <!-- <a href="{!!url('admin/patients')!!}" class="small-box-footer">See all Users &nbsp;<span class="fa fa-arrow-circle-right"></span></a> -->
                </div>
            </div><!-- ./col -->
           
            <div class="col-lg-4 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-fuchsia">
                    <div class="inner">
                        <h3>{!! $totalrides !!}</h3>
                        <p>Total Rides Published<br><br></p>
                    </div>
                    <div class="icon">
                        <span class="ion ion-person-add"></span>
                    </div>
                    <!-- <a href="{!!url('admin/doctors')!!}" class="small-box-footer">{!! trans('admin/dashboard.go_to') !!} <span class="fa fa-arrow-circle-right"></span></a> -->
                </div>
            </div><!-- ./col -->

            <div class="col-lg-4 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-purple">
                    <div class="inner">
                        <h3>{!! $totalridescompleted !!}</h3>
                        <p>Total Rides Completed<br><br></p>
                    </div>
                    <div class="icon">
                        <span class="ion ion-bookmark"></span>
                    </div>
                    <!-- <a href="{!!url('admin/appointments')!!}" class="small-box-footer">{!! trans('admin/dashboard.go_to') !!} <span class="fa fa-arrow-circle-right"></span></a> -->
                </div>
            </div><!-- ./col -->
            <div class="col-lg-4 col-xs-6">
                <div class="small-box bg-fuchsia">
                    <div class="inner">
                        <h3>{!! $transactions !!}</h3>
                        <p>Total Transactions<br><br></p>
                    </div>
                    <div class="icon">
                        <span class="ion ion-cash"></span>
                    </div>
                    <!-- <a href="{!!url('admin/transaction')!!}" class="small-box-footer">{!! trans('admin/dashboard.go_to') !!} <span class="fa fa-arrow-circle-right"></span></a> -->
                </div>
            </div>
            
            <!-- ./col -->
           <div class="col-lg-4 col-xs-6">
                <div class="small-box bg-purple">
                    <div class="inner">
                        <h3>{!! @$totalsignupusingreferral !!}</h3>
                        <p>Total Signups using Referral Codes<br><br></p>
                    </div>
                    <div class="icon">
                        <span class="ion ion-email"></span>
                    </div>
                    <!-- <a href="{!!url('admin/enquiry')!!}" class="small-box-footer">{!! trans('admin/dashboard.respond_now') !!} <span class="fa fa-arrow-circle-right"></span></a> -->
                </div>
            </div>
            <!-- ./col -->
        </div><!-- /.row -->
        <!-- Main row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
@stop

resources/views/admin/forgotPassword.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{!! trans('admin/login.sitename') !!} :: {!! trans('admin/login.sign_in') !!}</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        
        <link rel="shortcut icon" href="{!!asset('assets/admin/logo.png')!!}"  >
        
        <!-- bootstrap 3.2.0 -->
        <link href="{!! asset('assets/admin/bootstrap/css/bootstrap.min.css')!!}" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="{!! asset('assets/admin/font-awesome/css/font-awesome.min.css')!!}" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="{!!asset('assets/admin/dist/css/AdminLTE.min.css')!!}" rel="stylesheet" type="text/css" />
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <link href="{!!asset('assets/admin/css/style.css')!!}" rel="stylesheet" type="text/css" />
    </head>
    <body>

    <nav class="navbar navbar-expand-md navbar-light mb-3">
    <div class="container-fluid">
        <a href="#" class="navbar-brand mr-3"><img  src="{{ url('assets/admin/logo.png') }}" height="80px" alt="image"></a>
    </div>    
</nav>


    <div class="jumbotron" style="background-color:white;">
        <div class="row">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-6">
                <img src="{{ url('assets/admin/carpool.png') }}" height="400px" alt="image">
            </div>
            <div class="col-sm-3">
                <h2 class="text-center">Forgot Password</h2>
                
                    <!-- <div class="form-row">
                      <div>
                        <label class="sr-only" for="inlineFormInputGroupUsername">Username</label>
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <div class="input-group-text">Phone Number</div>
                          </div>
                          <input type="text" class="form-control" id="inlineFormInputGroupUsername">
                        </div>
                      </div>
                      &nbsp;&nbsp;&nbsp;
                      <button class="btn" type="submit" style="background-color: rgb(193, 9, 88); color: white;">Login/Register</button>
                    </div> -->

        <div class="login-box">
            <!-- Notifications -->
                @include('admin.includes.notifications')
            <!-- ./ notifications -->
            {!! Form::open(array('method' => 'POST','url' => 'admin/password/email', 'id' => 'login-form','novalidate' => 'novalidate')) !!}
            <div class="form-group has-feedback form-feedback">
                {!! Form::number('phone_number', null,array('class'=>'form-control', 'placeholder' => 'Phone Number')) !!}
                <span class="glyphicon glyphicon-phone form-control-feedback"></span>
            </div>
               
                   
                    <div class="row">
                        <div class="col-xs-6">
                            {!! Form::submit(trans('admin/common.submit'), array('class'=>'btn bg-blue-gradient btn-block')) !!}
                        </div>
                        <div class="col-xs-6">
                            <a href="{!!URL::to('admin/')!!}" class="btn btn-danger btn-block">{!! trans('admin/common.cancel') !!}</a>
                        </div>
                        
                    </div>
                {!! Form::close() !!}
            </div><!-- /.login-box-body -->
        </div><!-- /.login-box -->

        <!-- jQuery 2.1.4 -->
        <script src="{!!asset('assets/admin/plugins/jQuery/jQuery-2.1.4.min.js')!!}" type="text/javascript"></script>
        <!-- Bootstrap 3.3.2 JS -->
        <script src="{!!asset('assets/admin/bootstrap/js/bootstrap.min.js')!!}" type="text/javascript"></script>

        <!-- jQuery Validation js -->
        <script src="{!!asset('assets/admin/plugins/validation/jquery.validate.min.js')!!}" type="text/javascript"></script>
        <script src="{!!asset('assets/admin/plugins/validation/additional-methods.js')!!}" type="text/javascript"></script>

        <!-- AdminLTE App -->
        <script src="{!!asset('assets/admin/dist/js/app.min.js')!!}" type="text/javascript"></script>
        <script src="{!!asset('assets/admin/js/common.js')!!}" type="text/javascript"></script>
    </body>
</html>
<script>
$(function () {
    //hide alert message when click on remove icon
    $(".close").click(function () {
        $(this).closest('.alert').addClass('hide');
    });
});
</script>

resources/views/admin/showReferral.blade.php
@extends('admin.layouts.default')

{{-- Web site Title --}}
@section('title')
@parent :: {!! trans('admin/generalSettings.settings') !!}
@stop
@section('styles')
@stop
{{-- Content --}}
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Referral Settings</h1>
        <!-- <ol class="breadcrumb">
            <li><a href="/admin"><span class="fa fa-dashboard"></span> {!! trans('admin/common.home') !!}</a></li>
            <li class="active">{!! trans('admin/generalSettings.settings') !!}</li>
        </ol> -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <div class="col-md-12">
                <!-- Notifications -->
                @include('admin.includes.notifications')
                <!-- ./ notifications -->
            </div>
            <div class="col-xs-12">
                <div class="box">
                @if(isset($data))
                    {!! Form::model($data, array('url' => 'admin/referralSettings', 'method' => 'POST', 'id' => 'updateBrand-form', 'files' => true )) !!}
                 
                    @else
                    {!! Form::open(array('url' => 'admin/addBrand', 'id' => 'addBrand-form','method'=>'POST', 'files' => true)) !!}
                @endif    
                {!! Form::open(array('method' => 'POST','url' => 'admin/referralSettings', 'id' => 'referralForm')) !!}
                     
                
                    <div class="box-body">
                        <div class="form-group has-feedback">
                            {!! Form::label('referral_code_text', 'Referral Default Text') !!}
                            {!! Form::text('referral_code_text', old('referral_code_text'),array('class'=>'form-control' )) !!}
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <div class="form-group has-feedback">
                            {!! Form::label('referral_code_discount', 'Referral Discount : (Percentage)') !!}
                            {!! Form::text('referral_code_discount', old('referral_code_discount'),array('class'=>'form-control' )) !!}
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                        
                    <div class="box-footer">
                        {!! Form::submit('Save',array('class'=>'btn btn-primary', 'id'=>'submitform')) !!}
                        <a href="{!! URL::route('settings.index') !!}" class="btn btn-default">{!! trans('Cancel') !!}</a>
                    </div>    
                    {!! Form::close()!!}
                </div> <!-- /.box -->
            </div> <!-- /.col-xs-12 -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
@stop
{{-- Scripts --}}
@section('scripts')
 
@stop

resources/views/admin/showRideSettings.blade.php
@extends('admin.layouts.default')

{{-- Web site Title --}}
@section('title')
@parent :: {!! trans('admin/generalSettings.settings') !!}
@stop
@section('styles')
@stop
{{-- Content --}}
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Ride Related Settings</h1>
        <!-- <ol class="breadcrumb">
            <li><a href="/admin"><span class="fa fa-dashboard"></span> {!! trans('admin/common.home') !!}</a></li>
            <li class="active">{!! trans('admin/generalSettings.settings') !!}</li>
        </ol> -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <div class="col-md-12">
                <!-- Notifications -->
                @include('admin.includes.notifications')
                <!-- ./ notifications -->
            </div>
            <div class="col-xs-12">
                <div class="box">
                @if(isset($data))
                    {!! Form::model($data, array('url' => 'admin/rideSettings', 'method' => 'POST', 'id' => 'updateBrand-form', 'files' => true )) !!}
                 
                    @else
                    {!! Form::open(array('url' => 'admin/addBrand', 'id' => 'addBrand-form','method'=>'POST', 'files' => true)) !!}
                @endif    
                {!! Form::open(array('method' => 'POST','url' => 'admin/rideSettings', 'id' => 'referralForm')) !!}
                     
                
                    <div class="box-body">
                    <div class="form-group has-feedback">
                            {!! Form::label('sug_price_value', 'Suggested Price  : (Per KM.)') !!}
                            {!! Form::number('sug_price_value', old('sug_price_value'),array('class'=>'form-control','step' => '.01' )) !!}
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <div class="form-group has-feedback">
                            {!! Form::label('ride_time_diff_search', 'Time Difference While Searching For Rides : (Hours)') !!}
                            {!! Form::number('ride_time_diff_search', old('ride_time_diff_search'),array('class'=>'form-control' )) !!}
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <div class="form-group has-feedback">
                            {!! Form::label('before_pass_cancel_time', 'Time Before a passenger can cancel Ride Offered : (Minutes)') !!}
                            {!! Form::number('before_pass_cancel_time', old('before_pass_cancel_time'),array('class'=>'form-control' )) !!}
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <div class="form-group has-feedback">
                            {!! Form::label('before_driv_cancel_time', 'Time Before a Driver can cancel Ride Requested : (Minutes) ') !!}
                            {!! Form::number('before_driv_cancel_time', old('before_driv_cancel_time'),array('class'=>'form-control' )) !!}
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                    <div class="box-footer">
                        {!! Form::submit('Save',array('class'=>'btn btn-primary', 'id'=>'submitform')) !!}
                        <a href="{!! URL::route('settings.index') !!}" class="btn btn-default">{!! trans('Cancel') !!}</a>
                    </div>    
                    {!! Form::close()!!}
                </div> <!-- /.box -->
            </div> <!-- /.col-xs-12 -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
@stop
{{-- Scripts --}}
@section('scripts')
 
@stop

resources/views/admin/userChart.blade.php
@extends('admin.layouts.default')

{{-- Web site Title --}}
@section('title')
@parent :: {!! trans('admin/service.services') !!}
@stop
@section('styles')
@stop
{{-- Content --}}
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Edit User</h1>


        <!-- <ol class="breadcrumb">
                <li><a href="/admin"><span class="fa fa-dashboard"></span> {!! trans('admin/common.home') !!}</a></li>
                <li class="active">{!! trans('admin/service.services') !!}</li>
            </ol> -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <div class="col-md-12">
                <!-- Notifications -->
                @include('admin.includes.notifications')
                <!-- ./ notifications -->
            </div>
            <div class="col-xs-12">
                <div class="box">
                    

                   <div class="card-body">

                    <h1>{{ $chart1->options['chart_title'] }}</h1>
                    {!! $chart1->renderHtml() !!}

                </div>
					 
                </div> <!-- /.box -->
            </div> <!-- /.col-xs-12 -->
        </div><!-- /.row (main row) -->
		
		 {!! $chart1->renderChartJsLibrary() !!}
{!! $chart1->renderJs() !!}
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

@stop